### ISSUE TITLE
Add import of “teacher’s timetable slots”

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#82] opened 2014-12-03 20:46 UTC
See [this](https://kosapi.fit.cvut.cz/projects/kosapi/wiki/Teachers#GET-teachersusernameOrIdtimetable) resource in KOSapi.

**Comment by flexik** [comment] 2015-11-12 18:45
Duplicate of #142.

**Closed by flexik** 2015-11-12 18:45 UTC
Labels: enhancement
